default:
  # --- Django ---
  # https://docs.djangoproject.com/en/4.0/ref/settings/
  DEBUG: false
  SECRET_KEY:
  ROOT_URLCONF: qtcloud_payments.urls
  WSGI_APPLICATION: qtcloud_payments.wsgi.application
  ALLOWED_HOSTS:
    - '*'
  INTERNAL_IPS:
    - '127.0.0.1'
    - 'localhost'
  INSTALLED_APPS:
    # 官方
    - django.contrib.contenttypes
    - django.contrib.staticfiles
    # 第三方
    - rest_framework
    - corsheaders  # CORS策略
    - django_tenants
    - dynamic_initial_data
    - djmoney
    # 自建
    - tenants
    - products
    - orders
    - wallets
  MIDDLEWARE:
    # https://docs.djangoproject.com/en/4.0/ref/middleware/#middleware-ordering
    - django_tenants.middleware.main.TenantMainMiddleware
    - django.middleware.security.SecurityMiddleware
    - django.middleware.cache.UpdateCacheMiddleware
    # https://pypi.org/project/django-cors-headers/
    - corsheaders.middleware.CorsMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.middleware.cache.FetchFromCacheMiddleware
  DATABASES:
    default:
      ENGINE: django_tenants.postgresql_backend
      HOST:
      PORT: 5432
      USER: qtcloud_payments
      PASSWORD:
      NAME: qtcloud_payments
  DATABASE_ROUTERS:
    - django_tenants.routers.TenantSyncRouter
  CACHES:
    default:
      BACKEND: django.core.cache.backends.redis.RedisCache
      LOCATION:
  TEMPLATES:
    - BACKEND: django.template.backends.django.DjangoTemplates
      APP_DIRS: True
  STATIC_URL: /static/
  LANGUAGE_CODE: zh-Hans
  USE_I18N: true
  USE_L10N: true
  USE_TZ: false
  TIME_ZONE: Asia/Shanghai
  DEFAULT_AUTO_FIELD: django.db.models.BigAutoField

  # --- REST Framework ---
  # https://www.django-rest-framework.org/api-guide/settings/
  REST_FRAMEWORK:
    DEFAULT_AUTHENTICATION_CLASSES:
      # TODO: 引入drf-remote-auth的Authentication class
      - rest_framework.authentication.TokenAuthentication
    DEFAULT_PERMISSION_CLASSES:
      - rest_framework.permissions.AllowAny
    DEFAULT_RENDERER_CLASSES:
      - rest_framework.renderers.JSONRenderer
      - rest_framework.renderers.BrowsableAPIRenderer
      - rest_framework.renderers.AdminRenderer
    DEFAULT_PARSER_CLASSES:
      - rest_framework.parsers.JSONParser
    UNAUTHENTICATED_USER:
    TEST_REQUEST_DEFAULT_FORMAT: json
    TEST_REQUEST_RENDERER_CLASSES:
      - rest_framework.renderers.JSONRenderer

  # --- Django CORS ---
  CORS_ALLOW_ALL_ORIGINS: True

  # --- drf-admin ---
  DRF_ADMIN:
    DEFAULT_ADMIN_PERMISSION_CLASSES:
      # TODO: 接入鉴权系统以后改回默认值`IsAuthenticated`
      - rest_framework.permissions.AllowAny

  # --- djversion ---
  DJVERSION_GIT_REPO_PATH: BASE_DIR
  DJVERSION_GIT_USE_TAG: True

  # --- django-tenants ---
  TENANT_MODEL: tenants.Tenant
  TENANT_DOMAIN_MODEL: tenants.TenantDomain
  SHARED_APPS:
    # 官方
    - django.contrib.contenttypes
    - django.contrib.staticfiles
    # 第三方
    - rest_framework
    - corsheaders  # CORS策略
    - django_tenants
    - dynamic_initial_data
    - djmoney
    # 自建
    - tenants
  # tenant-specific apps
  TENANT_APPS:
    # 自建
    - products
    - orders
    - wallets

# ----- 开发环境 -----
development:
  DEBUG: true
  CACHE_MIDDLEWARE_SECONDS: 0  # 关闭pre-view缓存

# ----- 测试环境 -----
testing:
  CACHE_MIDDLEWARE_SECONDS: 0  # 关闭pre-view缓存

# ----- 生产环境 -----
production:
  CACHE_MIDDLEWARE_SECONDS: 600  # pre-view缓存时长为10分钟
