# Generated by Django 4.1.3 on 2022-11-21 17:40

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="租户ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                        verbose_name="租户标识",
                    ),
                ),
                ("verbose_name", models.CharField(max_length=256, verbose_name="租户名称")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="租户创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="租户修改时间"),
                ),
            ],
            options={
                "verbose_name": "租户",
            },
        ),
        migrations.CreateModel(
            name="TenantDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="租户域名ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True, max_length=253, unique=True, verbose_name="租户域名"
                    ),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="租户域名创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="租户域名修改时间"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                        verbose_name="关联租户",
                    ),
                ),
            ],
            options={
                "verbose_name": "租户域名",
            },
        ),
    ]
