# Generated by Django 3.2.10 on 2022-08-03 21:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='商品名称')),
                ('verbose_name', models.CharField(max_length=256, verbose_name='商品详细名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近编辑时间')),
                ('type', models.CharField(choices=[('goods', '实物商品'), ('service', '服务'), ('bundle', '商品组合')], max_length=16, verbose_name='商品类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('is_gift', models.BooleanField(default=False, verbose_name='是否为赠品')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
            ],
            options={
                'verbose_name': '商品',
                'ordering': ['updated_at'],
            },
        ),
    ]
